[package]
name = "balu"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = { version = "1.8.0", default-features = false }
smallvec = { version = "1.11.2", features = ["const_generics", "union"] }
